ansble/monument

- routes/index.js
> fixed... the bug closes #45"

- routes/index.js
> fixed the wild card route matching issue

- utils/send.js
> fixed the issue with temlpates and strings, seems to be working now

- routes/index.js
- utils/send.js
fixed several bugs including #61 and #71
> E3 harelbeke patch release

- app.js
- app_test.js
- readme.md
Allows for doTjs configuration options
> dotjs configs

- gulpfile.js
- gulpfile_test.js
agreed, a gulp module would be better :)
> modify gulp build to roll patch and minor versions when appropriate

- app.js
- package.json
updated the event-state version and re-released
> E3 harelbeke

- readme.md
- security/index.js
- security/publicKeyPinning.js
- security/publicKeyPinning_test.js
The details, which are significant are in the readme file. It's
a lot.
closes #123
> Adds Public Key Pinning support to monument

- readme.md
> Fixes typo in config object

- changes.md
Also removes that stuff from the readme so that it can act as basic
documentation and onboarding guide.
> Adds a changes.md file where human readable changlogs will be

- docs/routes.md
- docs/testing.md
- readme.md
- routes/router_test.js
And sets up a docs directory for more docs as we go forward
closes #136
> Adds documentation for testing

- index.js
- index_test.js
- package.json
- readme.md
This will be useful for new item handling and various other
things.
> Adds a UUID generator to monument

- utils/tools.js
- utils/tools_test.js
I was using not(isDefined()) a ton and figured a better convenience
would be to just have a function for checking undefined
> Adds an isUndefined function

- docs/Monument-in-action.md
- docs/routes.md
- readme.md
> Starts the revision of the routes docs

- readme.md
> Updates typos and heading inconsistency

- contributing.md
- readme.md
Adds a contributing.md file with contributing information, and a
Table of contents to the readme file. Also cleans up the documentation
a bit.
> Closes #172 and gets documentation ready for the release of 2.2.0

- package.json
The previous version had a security vulnerability and it needed
to be patched.
closes #184
> Upgrades the version of ws in use

- package.json
- test_stubs/formDataBody.txt
- utils/parseForm_test.js
- utils/parser.js
- utils/parser_test.js
`busboy` is replacing `raw-body` as the form parse handler. It adds a bunch of features and is very widely used.
closes #178
> Adds busboy and rewrites form parsing to handle files

- readme.md
Added [![Known Vulnerabilities](https://snyk.io/test/npm/monument/badge.svg)](https://snyk.io/test/npm/monument) to readme.md
> Fix Issue #234: Add a known vulnerabilities badge

- utils/send.js
Closes #202
After careful consideration pattern used here is prefered
over that suggested in the TODO
> Removes a TODO

- changes.md
- readme.md
it also removes some stuff from the readme.md that was
outdated
> Adds details of brotli to the changes

- index.js
- index_test.js
- routes/routeStore.js
- routes/routeStore_test.js
- routes/router.js
- routes/router_test.js
Closes #166
This is the big first commit for the route api. It switches most
of the places over to it. There may be a few places that need to
still be switched over and a search through the code base will be
needed to ensure that they are all found.
The other thing that needs to be done is the tests are still in
need of completion. Mainly this has to do with the API for removing
a route, since their is no where that does that in the code base
itself.
Other then that the server is working with the new API in place and
can run. So this is probably pretty close to what it is going to
end up looking like.
> Adds the routes API

- readme.md
repointing #276 to 2.4.x branch
> Issue #258 solved!

- AUTHORS
- changes.md
- docs/writing-route-handlers.md
- history.md
- readme.md
> Adds documentation for routes and other things

- AUTHORS
- changes.md
- docs/writing-route-handlers.md
- history.md
- package.json
- readme.md
- routes/router.js
- utils/setStatus.js
- utils/setStatus_test.js
TODOs:
<del>- [ ] update note about current release branch</del>
> Vattenfall 2.5.x

- package.json
simple update to a few dependencies
> Vattenfall 2.5.3 release

- history.md
- package.json
patch release to upgrade some build pipeline libs
> Coppa ugo agostoni 2.6.5

- history.md
- package.json
updates the version of ws that is being used to latest.
> Coppa ugo agostoni 2.6.12

- history.md
- package.json
Updates a bunch of dependencies all at once
> Coppa ugo agostoni 2.6.14 and 2.6.15 releases

- history.md
- package.json
Updates version of chai in use
> Coppa ugo agostoni 2.6.16

- history.md
- package.json
This fixes a security vulnerability caused by the `mime` dependency. Upgrade as soon as you can
> Tre valli varesine 3.1.8

- package-lock.json
- package.json
#429 
Anything wrong? I wasn't sure about line 68 and the `^`.
Edit: added a package-lock file
> Locked down dependencies version.

- routes/serverSetup.js
- routes/serverSetup_test.js
The exception thrown is expected as we're passing in the invalid directories in the tests, etc.
> Fixes #441 removes the console log error from the test

- history.md
- package.json
> Bretagne classic 3.2.5

- history.md
- package.json
- web-sockets/socketHandler_test.js
Thanks to @lazycoder9 for improving test coverage!
> Bretagne classic 3.2.6

- history.md
- package.json
> Bretagne classic 3.2.7

- readme.md
In the Route API section, I added the path key to the connection object.
> Update documentation for connection.path

- package.json
> fix(package): update ws to version 3.3.1

- history.md
- package-lock.json
- package.json
> Grand prix cycliste de québec 3.3.6

- history.md
- package-lock.json
- package.json
updates mime to latest version
> Grand prix cycliste de québec 3.3.9

- history.md
- package-lock.json
- package.json
> Grand prix cycliste de québec 3.3.11

- bin/increment.test.js
- package-lock.json
- package.json
- routes/handleStaticFile.test.js
- routes/matchSimpleRoute.test.js
- routes/parseWildCardRoute.test.js
- routes/performanceHeaders.test.js
- routes/routeStore.getStandard.test.js
- routes/routeStore.test.js
- routes/router.basic.route.test.js
- routes/router.statsd.test.js
- routes/routerStore.get.test.js
- routes/routerStore.getWildcard.test.js
- routes/routerStore.parse.test.js
- routes/routerStore.remove.test.js
- routes/serverSetup.test.js
- utils/config.test.js
- utils/index.test.js
- utils/parseForm.test.js
- utils/parser.test.js
- utils/redirect.test.js
- utils/send.test.js
- utils/setStatus.test.js
- utils/setup.test.js
- utils/staticFileEtags.test.js
- utils/statsd.test.js
- utils/tools.test.js
- utils/url.test.js
- yarn.lock
and chai as dependencies since they are unused
> removes mocha

- history.md
- package-lock.json
- package.json
Updates `platform`, `harken`, and the CSP library.
Platform is used with the CSP library to generate correct CSP headers.
No additions or breaking changes here that we use or expose.
> Grand prix cycliste de québec 3.3.16 & 3.3.17

- package.json
> fix(package): update iltorb to version 2.0.5

- package.json
> fix(package): update mime to version 2.2.2

- history.md
- package-lock.json
- package.json
> Paris–brussels 5.0.9

- history.md
- package-lock.json
- package.json
- routes/handleStaticFile.test.js
- test_stubs/static/default.js
- test_stubs/static/example.js
Fixes test build and upgrades dependencies.
> Paris–brussels 5.0.11

- history.md
- package-lock.json
- package.json
- readme.md
- routes/router.js
- routes/router.statsd.test.js
- routes/serverSetup.test.js
- utils/config.js
- utils/setStatus.test.js
- utils/statsd.js
- utils/statsd.test.js
minor fixes, dep updates and security
> Paris–brussels 5.1.2

- package.json
> chore(package): update utf-8-validate to version 5.0.1

- package.json
> fix(package): update ws to version 6.0.0

- readme.md
Greetings from Hacktoberfest event in Warsaw
>  Moving to a new line
